### ISSUE TITLE
install base results in parse error

### ISSUE THREAD

**Issue by mn200** [gilith/opentheory#10]
```
$ bin/polyml/opentheory install base
auto-initialized package repo {/Users/michaeln/.opentheory}

FATAL ERROR: opentheory failed:
error in package list "/Users/michaeln/.opentheory/repos/gilith.pkg" around line 1:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
parse error
package name install failed
```
Running from the root directory of the unpacked tar-file after what appears to be a successful (Poly/ML) build (`opentheory help` worked). On an M1 MacBook Pro (Apple Silicon), with Poly/ML `--version` = 
```
Poly/ML 5.9.1 Testing (Git version v5.9-184-gbafe319b)
```

**Comment by gilith** [comment]
Thanks for reporting this. I'm pretty sure the root cause is me converting the Gilith OpenTheory repo from HTTP to HTTPS a while ago, but for random reasons I won't have access to provide a fix until next week

**Comment by gilith** [comment]
I've just made a release of the opentheory tool that updates the URLs from HTTP to HTTPS and now I can install base without errors.

If you have an existing repo you can manually edit the ~/.opentheory/config file to convert all occurrences of http for the gilith domain to https, run opentheory update, and then the repo should work again

**Comment by mn200** [comment]
Thanks!  `install base` is now chugging away happily.
