### ISSUE TITLE
Test errors at the end of building process

### ISSUE THREAD

**Issue by binghe** [gilith/opentheory#3]
Hi,

It's been like this for several months. When I execute "make" from clean opentheory source directory, at the end I got some strange error outputs like this:

```
*** /tmp/golden-reference	2018-05-24 00:01:59.000000000 +0200
--- /tmp/test-output	2018-05-24 00:01:59.000000000 +0200
***************
*** 441,451 ****
  
  [license]
  name = MIT
! url = http://www.gilith.com/opentheory/licenses/MIT.txt
  
  [license]
  name = HOLLight
! url = http://www.gilith.com/opentheory/licenses/HOLLight.txt
  
  [cleanup]
  auto = 3600
--- 441,451 ----
  
  [license]
  name = MIT
! url = http://www.gilith.com/research/opentheory/licenses/MIT.txt
  
  [license]
  name = HOLLight
! url = http://www.gilith.com/research/opentheory/licenses/HOLLight.txt
  
  [cleanup]
  auto = 3600
make[2]: *** [mlton-diff] Error 1
make[1]: *** [mlton] Error 2
make: *** [default] Error 2
```

It doesn't stop me using opentheory, because the main binary is well built. But what's above error? Is it also happening on your side?

Regards,

Chun Tian

**Comment by gilith** [comment]
Hi Chun Tian,

I changed some paths a while ago that would cause these tests to fail. The solution is to reinitialize your development snapshot using

`make init`

Please let me know if that doesn't fix the problem.

Cheers,

Joe

**Comment by binghe** [comment]
Thanks! Now the errors are gone after your following suggestions. Consider the issue is closed.
