### ISSUE TITLE
Failure to build with MLton, which complains “strange constant”

### ISSUE THREAD

**Issue by Hibou57** [gilith/opentheory#4]
Trying to build the latest OpenTheory with the latest MLton, `make` terminates with exit code 2 and this message:

    bin/mlton/selftest
    cd bin/mlton ; mlton -runtime 'ram-slop 0.4' selftest.mlb
    unhandled exception: Fail: Ssa.Shrink.simplifyCases: strange constant
    Makefile:180 : la recette pour la cible « bin/mlton/selftest » a échouée
    make: *** [bin/mlton/selftest] Erreur 1
    rm bin/mlton/selftest.sml bin/mlton/selftest.mlb

Building with `polyml` seems OK. I don’t know if it’s an OpenTheory issue or an MLton isssue.

**Comment by gilith** [comment]
Hi Yannick,

Thanks for letting me know about this. What version of MLton are you using (the command mlton will tell you) and what platform are you on? I'm also using the latest version (on Debian Linux), and don't get this behavior.

It looks to me like a compiler bug, and here are [instructions](http://mlton.org/Bug) for reporting it. It doesn't appear to be in the list of [known compiler bugs](http://mlton.org/Bugs20130715) for this release.

Cheers,

Joe

**Comment by Hibou57** [comment]
Hello,

It just says “MLton ????????” (really, just question marks). MLton was built on 2019-03-30. I will later retry with MLton built from ZIP instead of from repository clone, since I already had an issue building HOL4 from clone.

**Comment by Hibou57** [comment]
Yes, it seems to be an MLton bug, which I just submitted: https://github.com/MLton/mlton/issues/294

OpenTheory 1.4 is built with no error using MLton 20180207.

Previously, I forget to tell about the platform: Ubuntu 16.04 on a 32 bits machine.

**Comment by Hibou57** [comment]
Just wanted to say the issue with MLton is fixed. I checked it indeed works now.

**Comment by gilith** [comment]
Thank you for reporting the resolution - good find!
