### ISSUE TITLE
infix notations?

### ISSUE THREAD

**Issue by c-cube** [gilith/opentheory#6]
I see that the tool is able to print the article's assumptions and theorems using nice sugared syntax, with binders, infix symbols, etc. Does it have special knowledge of symbols, or is there some sort of table of precedence/fixity somewhere?

**Comment by gilith** [comment]
The tool does have special knowledge of symbols, but only for the purposes of pretty-printing. For example, the known symbol names are defined here

https://github.com/gilith/opentheory/blob/523a6ea1b055d39706dbffae9f7fa97e467552b0/src/Namespace.sml#L110

and their infix precedence is defined here

https://github.com/gilith/opentheory/blob/523a6ea1b055d39706dbffae9f7fa97e467552b0/src/Term.sml#L1696

**Comment by c-cube** [comment]
Thank you, that makes sense.
